pipeline {

	agent { label 'maven' }
	
	stages {	
		stage('Test') {
			options { timeout(time: 50, unit: 'SECONDS') }
			steps {	
				dir('shopping-cart-v2') {
				sh './mvnw clean test'
				}
			}
		}

		stage('Build Image') {
			environment { QUAY = credentials('QUAY_USER')}
			steps {
				dir('shopping-cart-v2')	{
				  sh './mvnw quarkus:add-extension -Dextensions="kubernetes,container-image-jib" '
				  sh '''
				    ./scripts/build-and-push-image.sh \
				    -u $QUAY_USR \
				    -p $QUAY_PSW \
				    -b $BUILD_NUMER
				  '''
				}
			}
		}
		
		stage('Deploy') {
			environment = { QUAY = credentials('QUAY_USER') }
			steps { 
				dir('shopping-cart-v2') {
				  script {
				    def status = sh(
					script: ".scripts/-tag-exists-in-quay.sh $QUAY_USR/do400-recover latest",
					returnStatus: true
					)

				    if (status != 0) {
					error("Tag not found in Quay!")
					}
				  }

				sh './scripts/deploy-image.sh $APP_NAMESPACE'
				}
			}
		}
	}
}
