pipeline {

	agent { label 'maven' }
	
	stages {	
		stage('Test') {
			options { timeout(time: 50, unit: 'SECONDS') }
			steps {	
				dir('shopping-cart-v2') {
				sh './mvnw clean test'
				}
			}
		}

		stage('Build Image') {
			environment { QUAY = credentials('QUAY_USER')}
			steps {
				dir('shopping-cart-v2')	{
				  sh './mvnw quarkus:add-extension -Dextensions="kubernetes,container-image-jib" '
				  sh '''
				    ./scripts/build-and-push-image.sh \
				    -u $QUAY_USR \
				    -p $QUAY_PSW \
				    -b $BUILD_NUMER
				  '''
				}
			}
		}
	}
}
