pipeline {

	agent { label 'maven' }
	
	stages {	
		options { timeout(time: 50, unit: 'SECONDS') }
		stage('Test') {
			steps {	
				dir('shopping-cart-v2') {
				sh './mvnw clean test'
				}
			}
		}
	}
}
